import Head from "next/head";
import React from "react";
import Hero from "./hero";
import Navigation from "./navigation/";

interface Props {
  children: React.ReactNode;
}

const Layout = () => {
  return (
    <>
      <Head>
        <title>ODD</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <meta name="keywords" content="odd, odd app, odd app beta, odd app public beta, odd app public beta 2021, odd app public beta 2021" />
      </Head>
      <Navigation />
      <Main>
        <Hero />
      </Main>
    </>
  );
}

export default Layout;


const Main = ({ children }: Props) => {
  return (
    <main>
      {children}
    </main>
  )
}


